# ifndef TARGET
# TARGET=avr-RSS2
# endif

# # Make absolutely certain that you specify your device here
# #DEFINES+=MODEL_N740

# # These examples don't need code banking so we turn it off 
# #HAVE_BANKING=1

# CONTIKI_PROJECT += broadcast_message

# all: $(CONTIKI_PROJECT) hex

# hex: 
    # ihex blink_led.hex

CONTIKI = C:/contiki-RS
include $(CONTIKI)/Makefile.include
